export { default as Home } from './Home'
export { default as About } from './About'
export { default as Members } from './Members'
export { default as Events } from './Events'
export { default as Login } from './Login'
export { default as Admin } from './Admin'
export { default as AddMember } from './AddMember'
